return {
  "AstroNvim/astrocore",
  opts = {
    options = {
      opt = {
        autoindent = true,
        autoread = true,
        clipboard = "unnamedplus",
        colorcolumn = "80",
        encoding = "utf-8",
        expandtab = true,
        -- vim.opt.fileencoding = "utf-8",
        foldenable = false,
        foldmethod = "manual",
        guifont = "-misc-fixed-medium-r-normal-*-18-120-100-100-c-90-iso10646-1",
        guifontwide = "-misc-fixed-medium-r-normal-*-18-120-100-100-c-180-iso10646-1",
        -- vim.opt.guicursor = "",
        hidden = true,
        hlsearch = true,
        laststatus = 3,
        mouse = "nc",
        nu = true,
        rnu = true,
        ruler = true,
        scrolloff = 3,
        shiftwidth = 4,
        showmode = false,
        signcolumn = "yes",
        smartindent = true,
        smarttab = true,
        splitbelow = true,
        splitright = true,
        swapfile = false,
        tabstop = 4,
        termguicolors = true,
        title = true,
        textwidth = 80,
        undofile = true,
        undolevels = 100,
        undoreload = 1000,
      },
    },
  },
}
