return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cmake",
      "cpp",
      "css",
      "fish",
      "glsl",
      "go",
      "haskell",
      "html",
      "javascript",
      "latex",
      "lua",
      "meson",
      "nix",
      "rust",
      "scss",
      "toml",
      "typescript",
      "vim",
      "vue",
      "wgsl",
      "zig",
    },
    sync_install = false,
    auto_install = true,
    highlight = { enable = true, additional_vim_regex_highlighting = false },
  },
}
